saturncloud/dask-saturn

conda.recipe/meta.yaml, setup.py
@jsignell for your consideration...I think we should use the more specific license label in this project's conda recipe.
Since we use the 3-clause BSD, this recipe should reflect that. I know `BSD-3-Clause` is a valid label because I just submitted a personal project to `conda-forge` with it a week or two ago, and it's [the label from SPDX](https://spdx.org/licenses/BSD-3-Clause.html).
=> added more specific license label to conda recipe

.github/workflows/publish-to-pypi.yml, CONTRIBUTING.md
I am not sure how to test this. But ideally, when a new version is tagged this should kick off a github action that creates and uploads a package to pypi.
=> Add github action to publish to pypi on tag

dask_saturn/core.py
When creating and managing a cluster backed by Saturn, `dask-saturn` relies on two environment variables: `SATURN_TOKEN` and `BASE_URL`.
These are accessed today with `.get()`. I think the intention in making this lenient is to allow someone to create a `SaturnCluster` object without those variables.
However, I think we should at least warn when they are not set. I just found myself in a situation where `BASE_URL` was not set, and got this error message:
> requests.exceptions.MissingSchema: Invalid URL 'api/dask_clusters': No schema supplied. Perhaps you meant http://api/dask_clusters?
I think this would be confusing for someone who isn't really familiar with `dask-saturn`. Raising a warning would at least give them a good place to start.
If I'm wrong about it being desirable to be able …
=> add warnings about missing environment variables

dask_saturn/backoff.py, dask_saturn/core.py
This PR fixes these minor `flake8` things.
```
./dask_saturn/backoff.py:6:1: E302 expected 2 blank lines, found 1
./dask_saturn/backoff.py:22:1: W293 blank line contains whitespace
./dask_saturn/core.py:64:15: F541 f-string is missing placeholders
```
=> fix flake8 things

conda.recipe/meta.yaml
@jameslamb and I were going through the release steps and realized that with the addition of the most recent warnings you can no longer import dask-saturn if certain saturn-y env vars are not set. I am getting rid of the test in the recipe to reflect that.
=> Update recipe for 0.0.4

dask_saturn/backoff.py, dask_saturn/core.py
This pull requests proposes adding documentation including parameter descriptions and type hints, to improve the user experience with `dask-saturn` and make it easier to choose appropriate values for parameters.
Even though this project  doesn't have hosted documentation, these can still be read in the source code here on GitHub and in any Python REPL via `help(SaturnCluster)`.
=> add parameter docs, typehints

dask_saturn/core.py
In some cases a warning for dask cluster updates can be repeated while dask-saturn is wait-looping (e.g. attempting to update settings on a cluster that is already pending). This ensures that each warning will only be printed once.
So this:
```
[2020-07-13 20:44:45] WARNING - dask-saturn | Unable to update the specification of a running dask cluster. No changes applied. To update, first stop the cluster with `cluster.close()` and reinitialize, or run 'cluster = SaturnCluster.reset(**kwargs)' to restart automatically.
[2020-07-13 20:44:45] INFO - dask-saturn | Starting cluster. Status: pending
[2020-07-13 20:44:52] WARNING - dask-saturn | Unable to update the specification of a running dask cluster. No changes applied. To update, first stop the cluster with `cluster.close()` and …
```
=> Skip repeated warnings in wait loop

dask_saturn/__init__.py, dask_saturn/core.py
This PR proposes two tiny fixes to improve the usability of `dask-saturn`.
1. Fixes a typo in docs (`scheduler_size` documented as `worker_size`)
2. Adds `describe_sizes()` and `list_sizes()` to `__init__.py`. This allows you to do `from dask_saturn import describe_sizes`, Without this, you have to run `from dask_saturn.core import describe_sizes`.
=> fix parameter doc and import strategy

.github/workflows/main.yml, Makefile, dask_saturn/__init__.py, dask_saturn/_version.py, dask_saturn/backoff.py, dask_saturn/core.py, versioneer.py
This pull request proposes adding linting to `dask-saturn`, and a GitHub Actions job to run that on every PR. As of this writing, no checks are done on the code when PRs are submitted, and I believe this linting will help catch issues and give us higher confidence in releases.
linters added:
* `black`: auto formatting
* `flake8`: style suggestions and code correctness suggestions
* `pylint`: style suggestions and code correctness suggestions
**issues found by `flake8`**
```text
./dask_saturn/_version.py:254:94: E231 missing whitespace after ','
./dask_saturn/__init__.py:1:1: F401 '.core.describe_sizes' imported but unused
./dask_saturn/__init__.py:1:1: F401 '.core.list_sizes' imported but unused
./dask_saturn/__init__.py:1:1: F401 '.core.SaturnCluster' imported but unused
```
**issues …
=> add linting

dask_saturn/core.py
Hugo was running into an error when trying to use the context manager with `n_workers` set to > 0. I think in the past we had only really confirmed that this worked with adaptive clusters. So when the workers started being started at the same time as the scheduler it introduces a bit of a race condition. If the scheduler makes it up and is able to return a status before the workers make it up, then the assert will fail.This should fix that.
=> Don't assert that the cluster is running

dask_saturn/__init__.py, dask_saturn/core.py, dask_saturn/plugins.py
Ok so new approach, do the work in dask-saturn. To test this out make a new image with pip requirements like:
```
dask[complete]
git+https://github.com/saturncloud/dask-saturn.git@jsignell/register-plugin
```
Create a project with that image, open a notebook and run:
```python
from dask_saturn import SaturnCluster
from dask.distributed import Client
import pandas as pd
import dask.dataframe as dd
cluster = SaturnCluster(n_workers=1)
client = Client(cluster)
df = pd.DataFrame({'df': [1,2,3]})
ddf = dd.from_pandas(df, npartitions=1)
ddf = ddf.persist()
def helper2(fut):
return fut.compute()
fut2 = client.submit(helper2, ddf)
fut2.result()
```
=> Register plugin after start

.github/workflows/main.yml, dask_saturn/__init__.py, dask_saturn/plugins.py
This PR creates a new WorkerPlugin and a new top level method for uploading files to the workers.
Create a new image with requirements.txt like:
```
dask[complete]
git+https://github.com/saturncloud/dask-saturn.git@jsignell/datasets
```
Then open a notebook and spin up a cluster
```python
from dask_saturn import SaturnCluster
from distributed import Client
cluster = SaturnCluster()
client = Client(cluster)
```
Create a dir called data with some files in it.  Register `UploadFiles` and use `upload_files_to_workers` to pass the contents of `data` up to the workers.
```python
import os
from dask_saturn.plugins import UploadFiles, upload_files_to_workers
client.register_worker_plugin(UploadFiles())
upload_files_to_workers(client, "data")
client.run(os.listdir, "data")
```
Then scale down the …
=> Upload files to all workers, on start, and whenever

dask_saturn/plugins.py
This will resolve Module Not Found issues when the user syncs files to the workers.
To try this out we'll set up a project like
```
/home/jovyan/project/
|---- util/
|   |---- __init__.py
|   |---- hello.py
|
|---- Untitled.ipynb
```
Where hello.py is like:
```python
def greet():
return "Hello"
```
Then within the notebook do:
```python
import dask
from distributed import Client
from dask_saturn import SaturnCluster, RegisterFiles, sync_files
from util.hello import greet 
cluster = SaturnCluster()
client = Client(dask_cluster)
client.register_worker_plugin(RegisterFiles())
sync_files(client, "util")
dask_client.restart()
greet_task = dask.delayed(greet)()
dask.compute(greet_task)
```
=> Append cwd to python path in worker plugin

Makefile
The `envsubst` usage was needed when our repos depended on specific versions of `sutils` - now that this is no longer the case, our `conda-update` targets can be straightforward.
=> Simplify conda-update Makefile target

dask_saturn/core.py
Stemming from a discussion on `saturn-client`: https://github.com/saturncloud/saturn-client/pull/1#discussion_r545154513
This PR proposes removal of `logging` configuration. If used inside someone's application, this configuration will likely result in different log formats being used than other parts of the application, which can be rather painful to remove/coerce (like we do for `tornado`, `boto3`, and `alembic` in some of our codebases) if uniformity is required for log processing (as it is for some of our applications).
The consequences of this PR are small, but do exist - by default, `logging` only logs `WARNING` and above. We've been setting it to `INFO`- output would decrease unless configured.
=> Remove logger config

Makefile, dask_saturn/__init__.py, dask_saturn/core.py, dask_saturn/external.py, dask_saturn/settings.py
- Move settings into a class in its own file
- Add ExternalConnection class for configuring access to a Saturn dask cluster from outside of the Saturn installation
- Settings for project_id, base_url, saturn_token
- Generates client TLS key and CSR, requests signed certificate from Atlas
- Configures dask Security object for the SaturnCluster
- Add extra parameters on Atlas requests to enable the TCP+TLS proxy connection
=> [CU-5wgufp] external connection

.pre-commit-config.yaml, Makefile, pyproject.toml, setup.cfg
Moves configuration for `black`, `flake8`, and `pylint` out of `Makefile` and into root-level config files.
This makes the behavior of these linters consistent regardless of how you run them. Now the behavior from `make lint` will be the same as, say, `pylint prefect_saturn/`.
I chose to put as many as I could in `setup.cg` instead of introducing individual files like `.flake8` to minimize the number of files you have to think about.
=> centralize CI configs

dask_saturn/core.py
With a start script like: `pip install git+https://github.com/saturncloud/dask-saturn@jsignell/better-errors`
```python
from dask_saturn import SaturnCluster
SaturnCluster(n_workers="cat")
```
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-30ca30076ae4> in <module>
2 from dask_saturn import SaturnCluster
3 
----> 4 cluster = SaturnCluster(n_workers="foo")
5 client = Client(cluster)
6 cluster
/srv/conda/envs/saturn/lib/python3.7/site-packages/dask_saturn/core.py in __init__(self, n_workers, cluster_url, worker_size, worker_is_spot, scheduler_size, nprocs, nthreads, scheduler_service_wait_timeout, autoclose, external_connection, *args, **kwargs)
105 …
```
=> Improve error messages and check sizes before submitting

dask_saturn/core.py
Running https://github.com/saturncloud/examples/blob/main/examples/examples-cpu/prefect/prefect-cloud-scheduled-scoring.ipynb using `dask-saturn` 0.2.2, I ran into this error:
> Unexpected error: ValueError("Proposed scheduler_size: None is not a valid option. Options are: ['medium', 'large', 'xlarge', '2xlarge', '4xlarge', '8xlarge', '12xlarge', '16xlarge', 'g4dnxlarge', 'g4dn4xlarge', 'g4dn8xlarge', 'p32xlarge', 'p38xlarge', 'p316xlarge'].")
I think this is because the code in that notebook sets `worker_size` but not `scheduler_size`.
`None` should be a valid value for `scheduler_size`, since Saturn's back-end interprets that as "use the default size". This PR proposes fixing that check so that people using `SaturnCluster(worker_size="something")` don't run into this issue.
=> allow setting worker_size without also setting scheduler_size

.pre-commit-config.yaml, dask_saturn/core.py
This PR collapses the output from the `SaturnSetup` plugin so that it's less overwhelming.
=> [DEV-1757] Only output one line for success of worker plugins

README.md, dask_saturn/core.py, dask_saturn/settings.py
DEV-2442
This PR does a few things that all have to do with successfully creating self-closing dask clusters for individual prefect cloud flow runs. Specifically this PR:
- ensures that all prefect dask clusters have `autoclose=true`
- adds the prefectcloudflowrun_id to the body of the post when creating dask clusters.
- renames `autoclose` to `shutdown_on_close` since that is now an option in regular distributed
- uses the saturn version from the env vars to only pass new fields when Saturn is at its most recent. This means that this new version of dask-saturn should still work with older versions of Saturn.
- get on the this branch of saturn dask-cluster-per-run
- change your SATURN_VERSION to "2021.08.16" in .env_deps
- change this …
=> One dask cluster per prefect cloud flow run

dask_saturn/core.py
Addresses an error with dask[complete]>2021.08.01. 
There was a change to how the cluster widget was rendered in 2021.09.0 - it now requires a name. This adds that property so the widget renders properly and without error.
For DEV-2854
=> adding name property to SaturnCluster

.github/workflows/publish-to-pypi.yml, CONTRIBUTING.md
This PR:
- uses the template action from https://github.com/saturncloud/.github/blob/main/workflow-templates/publish-to-pypi.yml
- makes the user publish a release before the github action starts (rather than just pushing a tag)
=> Update publish action

dask_saturn/core.py
This happens frequently on main:
This is because it is now more common for workers to spin up after the plugin is registered. That is not an issue.
=> Remove 'no workers started up' warning

dask_saturn/core.py, dask_saturn/settings.py, setup.py
Since setuptools is now raising a warning, we need to update to using packaging.
=> Use packaging rather than distutils to get version

dask_saturn/core.py
This fixes the issue where the Cluster repr raises an error.
Before:
After:
=> Return None from `SaturnCluster.widget`
